```{r data generation, echo = FALSE, results = "hide"}
## DATA GENERATION
quiz <- c( "Option number 1.", "FALSE", "Feedback number 1.",
           "Option number 2.", "FALSE", "Feedback number 2.",
           "Option number 3.", "TRUE",  "Feedback number 3.",
           "Option number 4.", "FALSE", "Feedback number 4.",
           "Option number 5.", "FALSE", "Feedback number 5." )

quiz <- matrix( quiz, ncol = 3, byrow = TRUE )
questions <- quiz[ , 1 ]
solutions <- as.logical( quiz[ , 2 ] )
feedback <- quiz[ , 3 ]
randomQuiz <- sample( 1:5 )
questions <- questions[ randomQuiz ]
solutions <- solutions[ randomQuiz ]
feedback <- feedback[ randomQuiz ]
```

Question
========
Choose the answer with the number three.

```{r questionlist, echo = FALSE, results = "asis"}
answerlist( questions, markup = "markdown" )
```

Solution
========
It's very easy: one correct and talks about number three.

```{r solutionlist, echo = FALSE, results = "asis"}
answerlist( ifelse( solutions, "True", "False" ), markup = "markdown")
```

Meta-information
================
extype: schoice
exsolution: `r mchoice2string(solutions, single = TRUE)`
exname: Matrix example
